name: 2fa
description: $description
version: '${version}'

main: dev.toxi.twofa.TwoFactorPlugin
api-version: '1.21'
load: POSTWORLD

authors: [ TheToxi_LSD ]

# Регистрация команд сервера
commands:
  2fa:
    description: "Главная команда двухфакторной авторизации"
    aliases: [auth, verify]
    usage: "/2fa <enable|disable|unblock|reload>"

# Описание прав доступа для плагинов разрешений (например, LuckPerms)
permissions:
  2fa.command.enable:
    description: "Разрешает игрокам включать защиту 2FA через Discord"
    default: true
  2fa.command.disable:
    description: "Разрешает администраторам отключать 2FA у игроков"
    default: op
  2fa.command.unblock:
    description: "Разрешает администраторам снимать блокировки 2FA"
    default: op
  2fa.command.reload:
    description: "Разрешает администраторам перезагружать плагин и его сервисы"
    default: op
